### ISSUE TITLE
TEAM-LOGIN-03: Welcome pane

### ISSUE THREAD

**Issue by EmilyPascua** [csula-acm-upperclassman/Accord#3]
The welcome pane is immediately displayed after logging in. It can be seen as a splash screen.
- The welcome pane must include: the "welcome message" (to be decided by your team)
- ACM's current Logo
- Must include an animation on the welcome message and ACM logo, you can use a library for this: https://popmotion.io/pose/ or any animation library.

**Comment by treblegni** [comment]
No longer needed
