### ISSUE TITLE
PLC-0002: Server Navigation Pane

### ISSUE THREAD

**Issue by EmilyPascua** [csula-acm-upperclassman/Accord#5]
The server navigation pane displays all the servers (or rooms) the user has joined. If the user hasn't joined any room yet, then it should be empty. Test this with dummy data.

The server navigation pane must include the following buttons:
- Home button: To navigate to the home component.
- Server button: Use a for-loop and jsx to dynamically display multiple servers.

**Comment by EmilyPascua** [comment]
Related to #6.

**Comment by exelarios** [comment]
Here's the wireframe for the server navigation.

Notes:
- Use "display: d-flex" and "justify-content: center" to center and position the group icons.
- Make sure every element is website responsive.
- There's a way to create a gradient in CSS.

Color Palettes:
background-color: #1C1C1E;

Server Navigation Component 
<img width="1118" alt="server" src="https://user-images.githubusercontent.com/30312964/65931753-dac34600-e3bf-11e9-9ccb-643e8203c94b.png">

User Navigation:
Note: when the user clicks on their profile picture or name. It will toggle the menu.
<img width="1114" alt="servermenu" src="https://user-images.githubusercontent.com/30312964/65931864-2c6bd080-e3c0-11e9-84c2-d7e4b85df746.png">

Just create the status component for now and leave it static.

Color Palettes:
Blue: #3498DB;
Gray: #D8D8D8;
Red: #E74C3C;

If there's any miscommunicating or need some clarification please DM rin#0388

**Comment by treblegni** [comment]
No longer needed
